### PR TITLE
closes #78

### LINKED ISSUE #78: When searching for many tweets no categories are found
**Describe the bug**
In the tweet summary no category is found when the character count is too large.

**To Reproduce**
1. Go to home
2. Set the tweet count value to 100
3. Click on search
4. Observe the overall categories
5. Repeat step 1 to 4 until no categories are shown and check if we have categories for any tweet.

**Expected behavior**
If we have enough tweets, there should at least be one category shown.

One possible solution could be to only select a subset of all tweets for the overall category analysis.

**Additional content**
screen shot 2018-10-08 at 12 36 36
Having no category in the results may lead to this outcome.

### PR DESCRIPTION
**Pull request by itggot-kianoosh-geravesh**
## What issue did you implement or fix?
Fixed issue #78

## List of changes that were addressed in the issue.
- Added a better error text feedback.
- Added "count" and "lang" parameters to analyse function in _api.ts_.
- Added bunch of semicolons on the lines that were missing some.
- Added error icon to the error feedbacks.
- Fixed the error icon miss-alignment.

## How can this implementation be improved?
We could translate the tweets and run the search. This could lead to a better UX and more usefulness of the website.

### CODE REVIEW

File: src/api.ts [hunk 1]
```diff
@@ -5,42 +5,58 @@ const analysis_endpoint = `http://us-central1-saot-217513.cloudfunctions.net/sen
...
+        } else if (reason.response.data.details.includes("The language")) {
+            analysis[type] = "This languague is not supported by the program!";
+        } else {
+            analysis[type] = "There has been an error processing the search!";
+        }
+        Vue.set(doneStatus, type, true);
+    });
+};
+
+function analyser(type : string, count : any, analysis : any, data : any) {
```
Comment (itggot-linus-styren) [inline src/api.ts:26]: This should probably be English

File: src/api.ts [hunk 2]
```diff
@@ -5,42 +5,58 @@ const analysis_endpoint = `http://us-central1-saot-217513.cloudfunctions.net/sen
...
-    analysis[type] = reason.response.data.details;
-    Vue.set(doneStatus, type, true);
-  });
-}
+export function analyse(Vue : any, tweet : string, type : string, analysis : any, doneStatus : any, count : number | undefined = 0, lang : string | undefined = "en") {
+    axios.post(analysis_endpoint, {message: tweet, type: type, lang: lang}).then((resp) => {
+        analysis[type] = analyser(type, count, analysis[type], resp.data);
+        Vue.set(doneStatus, type, true);
+    }).catch((reason) => {
+        if (reason.response.data.details == "Invalid text content: too few tokens (words) to process.") {
```
Comment (itggot-linus-styren) [inline src/api.ts:15]: This ought to be extracted to a helper method.

File: src/components/TweetDetails.vue [hunk 3]
```diff
@@ -28,27 +28,30 @@
                     ul(v-if="selected.entities.urls instanceof Array" v-for="(url, index) in selected.entities.urls" :key="index")
                         li
                             b-link(target="_blank" :href="url") {{ url }}
-            b-row
+            b-row(v-if="typeof analysis.sentiment != 'string'")
```
Comment (itggot-linus-styren) [inline src/components/TweetDetails.vue:31]: you can also use `analysis.sentiment instanceof String`

**Review by itggot-linus-styren — APPROVED** [review]
Looks good, could be made more consistent with other code, but this shall be the focus of release 0.3

**Comment by itggot-linus-styren** [comment]
closes #78
