### PR TITLE
fixed #79

### LINKED ISSUE #79: When no tweets are returned the loading icon never disappears.
**Describe the bug**
When searching for some keywords that return no result, we do not get any text telling the user that no tweets were found and instead a loading icon is shown forever.

**To Reproduce**
1. Go to home
2. Search for keyword that no one has tweeted about (e.g a long random string)
3. Observe the loading icon for tweet list

**Expected behavior**
We should get an appropriate text telling the user no tweets were found matching the query. The summary shouldn't be shown if we have no tweets.

### PR DESCRIPTION
**Pull request by itggot-kianoosh-geravesh**
## What issue did you implement or fix?
Fixed issue #79

## List of changes that were addressed in the issue.
- Added a feedback text for no search results
- Added faExclamationCircle to our font-awesome library

## How can this implementation be improved?
- Better styling for the text feedback

### CODE REVIEW

File: src/views/Tweets.vue [hunk 1]
```diff
@@ -61,18 +62,21 @@ export default class Tweets extends Vue {
   search(query : string) {
     tsearch(query).then((response : any) => {
       this.tweets = this.parse_tweets_json(response.data);
-      this.analyseAllTweets();
+      if (this.tweets.length == 0) {
+        this.done = true;
+        this.summaryDone.sentiment = true;
```
Comment (itggot-linus-styren) [inline src/views/Tweets.vue:67]: We could create a helper function for this to reduce duplicated code.

**Review by itggot-linus-styren — APPROVED** [review]
Good, but can be improved.

**Comment by itggot-linus-styren** [comment]
closes #79
