### PR TITLE
fixed #76

### LINKED ISSUE #76: Searching with empty text
**Describe the bug**
The user is able to click search even if no text is provided.

**To Reproduce**
1. Go to home
2. Remove search text
3. Click the search button

**Expected behavior**
The search button should be disabled when no search query is provided.

### PR DESCRIPTION
**Pull request by itggot-kianoosh-geravesh**
## What issue did you implement or fix?
Fixed issue #76

## List of changes that were addressed in the issue.
- Added disable parameter to search button

### CODE REVIEW

File: src/router.ts [hunk 1]
```diff
@@ -20,7 +20,7 @@ export default new Router({
     {
       path: '/about',
       name: 'about', 
-      component: () => import('./views/about.vue')
+      component: () => import('./views/About.vue')
```
Comment (itggot-linus-styren) [inline src/router.ts:23]: Did you also rename the file from "about.vue" to "About.vue"?

**Review by itggot-linus-styren — CHANGES_REQUESTED** [review]
Almost perfect.

**Comment by itggot-linus-styren** [comment]
closes #76
